#!/bin/sh
# $Id: exchangeServer,v 1.0 2017/03/02 14:42:01 Nikolay Nikolaev <evrinoma@gmail.com>
#
# exchangeServer Starts, Stops and Restart Simple Server.
#
### BEGIN INIT INFO
# Provides:          exchangeServer
# Required-Start:    $network $named $remote_fs $syslog $sshd
# Should-Start:
# Required-Stop:     $network $named $remote_fs $syslog $sshd
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Short-Description: Simple Server
# Description:       Starts the webserver.
### END INIT INFO

NAMESEARCH=exchangeServer
RETVAL=0

get_pid_server() {
local state=$(ps aux |  grep "$NAMESEARCH" | grep -v grep  | awk '{printf "%s ", $2}') 
echo $state
}

state_server() {
local state=$(ps -e | grep $NAMESEARCH | awk '{print $1}') 
if [ -z  "$state" ] ; then
    return 0
else
    return 1
fi 
}

start() {
# Start daemons.
state_server
RETVAL=$?
if [ $RETVAL -eq 0 ]; then 
    echo -n $"Starting Web exchangeServer.... "
    nohup $NAMESEARCH -b > /dev/null 2>&1 &
    echo -e '\E[37;33m'"\033[1m\t\t\t\t\t\t\t\t\t\t\tdone\033[0m"
fi
}

stop() {
# Stop daemons.
state_server
RETVAL=$?
if [ $RETVAL -ne 0 ]; then 
    echo -n $"Shutting down Web exchangeServer: "
    local pid=$(get_pid_server)
    /bin/kill $pid && wait $pid 2>/dev/null 
    echo -e '\E[37;33m'"\033[1m\t\t\t\t\t\t\t\t\t\t\tdone\033[0m"
fi
}


status() {
# Status daemons.
echo -n $"Web exchangeServer is: "
state_server
RETVAL=$?
if [ $RETVAL  -eq 0 ] ; then
    echo -e '\E[37;29m'"\033[1m\t\t\t\t\t\t\t\t\t\t\t\tunused\033[0m"
    return 0
else
    echo -e '\E[37;31m'"\033[1m\t\t\t\t\t\t\t\t\t\t\t\trunning\033[0m"
    return 1
fi
}

# See how we were called.
case "$1" in
    start)
	    start
	;;
    stop)
	    stop
	;;
    restart)
	    stop
	    start
	;;
    status)
	    status
	;;
    *)
	echo "Usage: exchangeServer {start|stop|restart|status}"
	exit 1
    esac
exit $?
